name = "p_ne_np"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["PNeNp"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
linter.all = false
linter.unusedSimpArgs = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"

[[lean_lib]]
name = "PNeNp"
